/* soapMediaBindingProxy.h
   Generated by gSOAP 2.8.0 from Onvif.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapMediaBindingProxy_H
#define soapMediaBindingProxy_H
#include "soapH.h"
class MediaBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'MediaBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	MediaBinding()
	{ soap = soap_new(); endpoint = "http://localhost:80"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
	{"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
	{"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
	{"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
	{"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
	{"ns5", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL},
	{"ns6", "http://schemas.xmlsoap.org/ws/2005/04/discovery", NULL, NULL},
	{"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
	{"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
	{"tt", "http://www.onvif.org/ver10/schema", NULL, NULL},
	{"ns2", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
	{"wsa", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL, NULL},
	{"ns3", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
	{"ns10", "http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding", NULL, NULL},
	{"ns11", "http://www.onvif.org/ver10/events/wsdl/EventBinding", NULL, NULL},
	{"tev", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL},
	{"ns12", "http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding", NULL, NULL},
	{"ns13", "http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding", NULL, NULL},
	{"ns14", "http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding", NULL, NULL},
	{"ns15", "http://www.onvif.org/ver10/events/wsdl/PullPointBinding", NULL, NULL},
	{"ns16", "http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding", NULL, NULL},
	{"ns17", "http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding", NULL, NULL},
	{"ns1", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
	{"ns18", "http://www.onvif.org/ver10/network/wsdl/RemoteDiscoveryBinding", NULL, NULL},
	{"ns19", "http://www.onvif.org/ver10/network/wsdl/DiscoveryLookupBinding", NULL, NULL},
	{"dn", "http://www.onvif.org/ver10/network/wsdl", NULL, NULL},
	{"ns8", "http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding", NULL, NULL},
	{"ns9", "http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding", NULL, NULL},
	{"tan", "http://www.onvif.org/ver20/analytics/wsdl", NULL, NULL},
	{"tds", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL},
	{"timg", "http://www.onvif.org/ver20/imaging/wsdl", NULL, NULL},
	{"tptz", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
	{"trt", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~MediaBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'GetVideoSources' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetVideoSources(_trt__GetVideoSources *trt__GetVideoSources, _trt__GetVideoSourcesResponse *trt__GetVideoSourcesResponse) { return soap ? soap_call___trt__GetVideoSources(soap, endpoint, NULL, trt__GetVideoSources, trt__GetVideoSourcesResponse) : SOAP_EOM; };
	/// Invoke 'GetAudioSources' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetAudioSources(_trt__GetAudioSources *trt__GetAudioSources, _trt__GetAudioSourcesResponse *trt__GetAudioSourcesResponse) { return soap ? soap_call___trt__GetAudioSources(soap, endpoint, NULL, trt__GetAudioSources, trt__GetAudioSourcesResponse) : SOAP_EOM; };
	/// Invoke 'CreateProfile' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__CreateProfile(_trt__CreateProfile *trt__CreateProfile, _trt__CreateProfileResponse *trt__CreateProfileResponse) { return soap ? soap_call___trt__CreateProfile(soap, endpoint, NULL, trt__CreateProfile, trt__CreateProfileResponse) : SOAP_EOM; };
	/// Invoke 'GetProfile' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetProfile(_trt__GetProfile *trt__GetProfile, _trt__GetProfileResponse *trt__GetProfileResponse) { return soap ? soap_call___trt__GetProfile(soap, endpoint, NULL, trt__GetProfile, trt__GetProfileResponse) : SOAP_EOM; };
	/// Invoke 'GetProfiles' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetProfiles(_trt__GetProfiles *trt__GetProfiles, _trt__GetProfilesResponse *trt__GetProfilesResponse) { return soap ? soap_call___trt__GetProfiles(soap, endpoint, NULL, trt__GetProfiles, trt__GetProfilesResponse) : SOAP_EOM; };
	/// Invoke 'AddVideoEncoderConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__AddVideoEncoderConfiguration(_trt__AddVideoEncoderConfiguration *trt__AddVideoEncoderConfiguration, _trt__AddVideoEncoderConfigurationResponse *trt__AddVideoEncoderConfigurationResponse) { return soap ? soap_call___trt__AddVideoEncoderConfiguration(soap, endpoint, NULL, trt__AddVideoEncoderConfiguration, trt__AddVideoEncoderConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'AddVideoSourceConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__AddVideoSourceConfiguration(_trt__AddVideoSourceConfiguration *trt__AddVideoSourceConfiguration, _trt__AddVideoSourceConfigurationResponse *trt__AddVideoSourceConfigurationResponse) { return soap ? soap_call___trt__AddVideoSourceConfiguration(soap, endpoint, NULL, trt__AddVideoSourceConfiguration, trt__AddVideoSourceConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'AddAudioEncoderConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__AddAudioEncoderConfiguration(_trt__AddAudioEncoderConfiguration *trt__AddAudioEncoderConfiguration, _trt__AddAudioEncoderConfigurationResponse *trt__AddAudioEncoderConfigurationResponse) { return soap ? soap_call___trt__AddAudioEncoderConfiguration(soap, endpoint, NULL, trt__AddAudioEncoderConfiguration, trt__AddAudioEncoderConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'AddAudioSourceConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__AddAudioSourceConfiguration(_trt__AddAudioSourceConfiguration *trt__AddAudioSourceConfiguration, _trt__AddAudioSourceConfigurationResponse *trt__AddAudioSourceConfigurationResponse) { return soap ? soap_call___trt__AddAudioSourceConfiguration(soap, endpoint, NULL, trt__AddAudioSourceConfiguration, trt__AddAudioSourceConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'AddPTZConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__AddPTZConfiguration(_trt__AddPTZConfiguration *trt__AddPTZConfiguration, _trt__AddPTZConfigurationResponse *trt__AddPTZConfigurationResponse) { return soap ? soap_call___trt__AddPTZConfiguration(soap, endpoint, NULL, trt__AddPTZConfiguration, trt__AddPTZConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'AddVideoAnalyticsConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__AddVideoAnalyticsConfiguration(_trt__AddVideoAnalyticsConfiguration *trt__AddVideoAnalyticsConfiguration, _trt__AddVideoAnalyticsConfigurationResponse *trt__AddVideoAnalyticsConfigurationResponse) { return soap ? soap_call___trt__AddVideoAnalyticsConfiguration(soap, endpoint, NULL, trt__AddVideoAnalyticsConfiguration, trt__AddVideoAnalyticsConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'AddMetadataConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__AddMetadataConfiguration(_trt__AddMetadataConfiguration *trt__AddMetadataConfiguration, _trt__AddMetadataConfigurationResponse *trt__AddMetadataConfigurationResponse) { return soap ? soap_call___trt__AddMetadataConfiguration(soap, endpoint, NULL, trt__AddMetadataConfiguration, trt__AddMetadataConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'RemoveVideoEncoderConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__RemoveVideoEncoderConfiguration(_trt__RemoveVideoEncoderConfiguration *trt__RemoveVideoEncoderConfiguration, _trt__RemoveVideoEncoderConfigurationResponse *trt__RemoveVideoEncoderConfigurationResponse) { return soap ? soap_call___trt__RemoveVideoEncoderConfiguration(soap, endpoint, NULL, trt__RemoveVideoEncoderConfiguration, trt__RemoveVideoEncoderConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'RemoveVideoSourceConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__RemoveVideoSourceConfiguration(_trt__RemoveVideoSourceConfiguration *trt__RemoveVideoSourceConfiguration, _trt__RemoveVideoSourceConfigurationResponse *trt__RemoveVideoSourceConfigurationResponse) { return soap ? soap_call___trt__RemoveVideoSourceConfiguration(soap, endpoint, NULL, trt__RemoveVideoSourceConfiguration, trt__RemoveVideoSourceConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'RemoveAudioEncoderConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__RemoveAudioEncoderConfiguration(_trt__RemoveAudioEncoderConfiguration *trt__RemoveAudioEncoderConfiguration, _trt__RemoveAudioEncoderConfigurationResponse *trt__RemoveAudioEncoderConfigurationResponse) { return soap ? soap_call___trt__RemoveAudioEncoderConfiguration(soap, endpoint, NULL, trt__RemoveAudioEncoderConfiguration, trt__RemoveAudioEncoderConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'RemoveAudioSourceConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__RemoveAudioSourceConfiguration(_trt__RemoveAudioSourceConfiguration *trt__RemoveAudioSourceConfiguration, _trt__RemoveAudioSourceConfigurationResponse *trt__RemoveAudioSourceConfigurationResponse) { return soap ? soap_call___trt__RemoveAudioSourceConfiguration(soap, endpoint, NULL, trt__RemoveAudioSourceConfiguration, trt__RemoveAudioSourceConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'RemovePTZConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__RemovePTZConfiguration(_trt__RemovePTZConfiguration *trt__RemovePTZConfiguration, _trt__RemovePTZConfigurationResponse *trt__RemovePTZConfigurationResponse) { return soap ? soap_call___trt__RemovePTZConfiguration(soap, endpoint, NULL, trt__RemovePTZConfiguration, trt__RemovePTZConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'RemoveVideoAnalyticsConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__RemoveVideoAnalyticsConfiguration(_trt__RemoveVideoAnalyticsConfiguration *trt__RemoveVideoAnalyticsConfiguration, _trt__RemoveVideoAnalyticsConfigurationResponse *trt__RemoveVideoAnalyticsConfigurationResponse) { return soap ? soap_call___trt__RemoveVideoAnalyticsConfiguration(soap, endpoint, NULL, trt__RemoveVideoAnalyticsConfiguration, trt__RemoveVideoAnalyticsConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'RemoveMetadataConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__RemoveMetadataConfiguration(_trt__RemoveMetadataConfiguration *trt__RemoveMetadataConfiguration, _trt__RemoveMetadataConfigurationResponse *trt__RemoveMetadataConfigurationResponse) { return soap ? soap_call___trt__RemoveMetadataConfiguration(soap, endpoint, NULL, trt__RemoveMetadataConfiguration, trt__RemoveMetadataConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'DeleteProfile' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__DeleteProfile(_trt__DeleteProfile *trt__DeleteProfile, _trt__DeleteProfileResponse *trt__DeleteProfileResponse) { return soap ? soap_call___trt__DeleteProfile(soap, endpoint, NULL, trt__DeleteProfile, trt__DeleteProfileResponse) : SOAP_EOM; };
	/// Invoke 'GetVideoSourceConfigurations' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetVideoSourceConfigurations(_trt__GetVideoSourceConfigurations *trt__GetVideoSourceConfigurations, _trt__GetVideoSourceConfigurationsResponse *trt__GetVideoSourceConfigurationsResponse) { return soap ? soap_call___trt__GetVideoSourceConfigurations(soap, endpoint, NULL, trt__GetVideoSourceConfigurations, trt__GetVideoSourceConfigurationsResponse) : SOAP_EOM; };
	/// Invoke 'GetVideoEncoderConfigurations' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetVideoEncoderConfigurations(_trt__GetVideoEncoderConfigurations *trt__GetVideoEncoderConfigurations, _trt__GetVideoEncoderConfigurationsResponse *trt__GetVideoEncoderConfigurationsResponse) { return soap ? soap_call___trt__GetVideoEncoderConfigurations(soap, endpoint, NULL, trt__GetVideoEncoderConfigurations, trt__GetVideoEncoderConfigurationsResponse) : SOAP_EOM; };
	/// Invoke 'GetAudioSourceConfigurations' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetAudioSourceConfigurations(_trt__GetAudioSourceConfigurations *trt__GetAudioSourceConfigurations, _trt__GetAudioSourceConfigurationsResponse *trt__GetAudioSourceConfigurationsResponse) { return soap ? soap_call___trt__GetAudioSourceConfigurations(soap, endpoint, NULL, trt__GetAudioSourceConfigurations, trt__GetAudioSourceConfigurationsResponse) : SOAP_EOM; };
	/// Invoke 'GetAudioEncoderConfigurations' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetAudioEncoderConfigurations(_trt__GetAudioEncoderConfigurations *trt__GetAudioEncoderConfigurations, _trt__GetAudioEncoderConfigurationsResponse *trt__GetAudioEncoderConfigurationsResponse) { return soap ? soap_call___trt__GetAudioEncoderConfigurations(soap, endpoint, NULL, trt__GetAudioEncoderConfigurations, trt__GetAudioEncoderConfigurationsResponse) : SOAP_EOM; };
	/// Invoke 'GetVideoAnalyticsConfigurations' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetVideoAnalyticsConfigurations(_trt__GetVideoAnalyticsConfigurations *trt__GetVideoAnalyticsConfigurations, _trt__GetVideoAnalyticsConfigurationsResponse *trt__GetVideoAnalyticsConfigurationsResponse) { return soap ? soap_call___trt__GetVideoAnalyticsConfigurations(soap, endpoint, NULL, trt__GetVideoAnalyticsConfigurations, trt__GetVideoAnalyticsConfigurationsResponse) : SOAP_EOM; };
	/// Invoke 'GetMetadataConfigurations' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetMetadataConfigurations(_trt__GetMetadataConfigurations *trt__GetMetadataConfigurations, _trt__GetMetadataConfigurationsResponse *trt__GetMetadataConfigurationsResponse) { return soap ? soap_call___trt__GetMetadataConfigurations(soap, endpoint, NULL, trt__GetMetadataConfigurations, trt__GetMetadataConfigurationsResponse) : SOAP_EOM; };
	/// Invoke 'GetVideoSourceConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetVideoSourceConfiguration(_trt__GetVideoSourceConfiguration *trt__GetVideoSourceConfiguration, _trt__GetVideoSourceConfigurationResponse *trt__GetVideoSourceConfigurationResponse) { return soap ? soap_call___trt__GetVideoSourceConfiguration(soap, endpoint, NULL, trt__GetVideoSourceConfiguration, trt__GetVideoSourceConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'GetVideoEncoderConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetVideoEncoderConfiguration(_trt__GetVideoEncoderConfiguration *trt__GetVideoEncoderConfiguration, _trt__GetVideoEncoderConfigurationResponse *trt__GetVideoEncoderConfigurationResponse) { return soap ? soap_call___trt__GetVideoEncoderConfiguration(soap, endpoint, NULL, trt__GetVideoEncoderConfiguration, trt__GetVideoEncoderConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'GetAudioSourceConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetAudioSourceConfiguration(_trt__GetAudioSourceConfiguration *trt__GetAudioSourceConfiguration, _trt__GetAudioSourceConfigurationResponse *trt__GetAudioSourceConfigurationResponse) { return soap ? soap_call___trt__GetAudioSourceConfiguration(soap, endpoint, NULL, trt__GetAudioSourceConfiguration, trt__GetAudioSourceConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'GetAudioEncoderConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetAudioEncoderConfiguration(_trt__GetAudioEncoderConfiguration *trt__GetAudioEncoderConfiguration, _trt__GetAudioEncoderConfigurationResponse *trt__GetAudioEncoderConfigurationResponse) { return soap ? soap_call___trt__GetAudioEncoderConfiguration(soap, endpoint, NULL, trt__GetAudioEncoderConfiguration, trt__GetAudioEncoderConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'GetVideoAnalyticsConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetVideoAnalyticsConfiguration(_trt__GetVideoAnalyticsConfiguration *trt__GetVideoAnalyticsConfiguration, _trt__GetVideoAnalyticsConfigurationResponse *trt__GetVideoAnalyticsConfigurationResponse) { return soap ? soap_call___trt__GetVideoAnalyticsConfiguration(soap, endpoint, NULL, trt__GetVideoAnalyticsConfiguration, trt__GetVideoAnalyticsConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'GetMetadataConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetMetadataConfiguration(_trt__GetMetadataConfiguration *trt__GetMetadataConfiguration, _trt__GetMetadataConfigurationResponse *trt__GetMetadataConfigurationResponse) { return soap ? soap_call___trt__GetMetadataConfiguration(soap, endpoint, NULL, trt__GetMetadataConfiguration, trt__GetMetadataConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'GetCompatibleVideoEncoderConfigurations' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetCompatibleVideoEncoderConfigurations(_trt__GetCompatibleVideoEncoderConfigurations *trt__GetCompatibleVideoEncoderConfigurations, _trt__GetCompatibleVideoEncoderConfigurationsResponse *trt__GetCompatibleVideoEncoderConfigurationsResponse) { return soap ? soap_call___trt__GetCompatibleVideoEncoderConfigurations(soap, endpoint, NULL, trt__GetCompatibleVideoEncoderConfigurations, trt__GetCompatibleVideoEncoderConfigurationsResponse) : SOAP_EOM; };
	/// Invoke 'GetCompatibleVideoSourceConfigurations' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetCompatibleVideoSourceConfigurations(_trt__GetCompatibleVideoSourceConfigurations *trt__GetCompatibleVideoSourceConfigurations, _trt__GetCompatibleVideoSourceConfigurationsResponse *trt__GetCompatibleVideoSourceConfigurationsResponse) { return soap ? soap_call___trt__GetCompatibleVideoSourceConfigurations(soap, endpoint, NULL, trt__GetCompatibleVideoSourceConfigurations, trt__GetCompatibleVideoSourceConfigurationsResponse) : SOAP_EOM; };
	/// Invoke 'GetCompatibleAudioEncoderConfigurations' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetCompatibleAudioEncoderConfigurations(_trt__GetCompatibleAudioEncoderConfigurations *trt__GetCompatibleAudioEncoderConfigurations, _trt__GetCompatibleAudioEncoderConfigurationsResponse *trt__GetCompatibleAudioEncoderConfigurationsResponse) { return soap ? soap_call___trt__GetCompatibleAudioEncoderConfigurations(soap, endpoint, NULL, trt__GetCompatibleAudioEncoderConfigurations, trt__GetCompatibleAudioEncoderConfigurationsResponse) : SOAP_EOM; };
	/// Invoke 'GetCompatibleAudioSourceConfigurations' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetCompatibleAudioSourceConfigurations(_trt__GetCompatibleAudioSourceConfigurations *trt__GetCompatibleAudioSourceConfigurations, _trt__GetCompatibleAudioSourceConfigurationsResponse *trt__GetCompatibleAudioSourceConfigurationsResponse) { return soap ? soap_call___trt__GetCompatibleAudioSourceConfigurations(soap, endpoint, NULL, trt__GetCompatibleAudioSourceConfigurations, trt__GetCompatibleAudioSourceConfigurationsResponse) : SOAP_EOM; };
	/// Invoke 'GetCompatibleVideoAnalyticsConfigurations' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetCompatibleVideoAnalyticsConfigurations(_trt__GetCompatibleVideoAnalyticsConfigurations *trt__GetCompatibleVideoAnalyticsConfigurations, _trt__GetCompatibleVideoAnalyticsConfigurationsResponse *trt__GetCompatibleVideoAnalyticsConfigurationsResponse) { return soap ? soap_call___trt__GetCompatibleVideoAnalyticsConfigurations(soap, endpoint, NULL, trt__GetCompatibleVideoAnalyticsConfigurations, trt__GetCompatibleVideoAnalyticsConfigurationsResponse) : SOAP_EOM; };
	/// Invoke 'GetCompatibleMetadataConfigurations' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetCompatibleMetadataConfigurations(_trt__GetCompatibleMetadataConfigurations *trt__GetCompatibleMetadataConfigurations, _trt__GetCompatibleMetadataConfigurationsResponse *trt__GetCompatibleMetadataConfigurationsResponse) { return soap ? soap_call___trt__GetCompatibleMetadataConfigurations(soap, endpoint, NULL, trt__GetCompatibleMetadataConfigurations, trt__GetCompatibleMetadataConfigurationsResponse) : SOAP_EOM; };
	/// Invoke 'SetVideoSourceConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__SetVideoSourceConfiguration(_trt__SetVideoSourceConfiguration *trt__SetVideoSourceConfiguration, _trt__SetVideoSourceConfigurationResponse *trt__SetVideoSourceConfigurationResponse) { return soap ? soap_call___trt__SetVideoSourceConfiguration(soap, endpoint, NULL, trt__SetVideoSourceConfiguration, trt__SetVideoSourceConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'SetVideoEncoderConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__SetVideoEncoderConfiguration(_trt__SetVideoEncoderConfiguration *trt__SetVideoEncoderConfiguration, _trt__SetVideoEncoderConfigurationResponse *trt__SetVideoEncoderConfigurationResponse) { return soap ? soap_call___trt__SetVideoEncoderConfiguration(soap, endpoint, NULL, trt__SetVideoEncoderConfiguration, trt__SetVideoEncoderConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'SetAudioSourceConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__SetAudioSourceConfiguration(_trt__SetAudioSourceConfiguration *trt__SetAudioSourceConfiguration, _trt__SetAudioSourceConfigurationResponse *trt__SetAudioSourceConfigurationResponse) { return soap ? soap_call___trt__SetAudioSourceConfiguration(soap, endpoint, NULL, trt__SetAudioSourceConfiguration, trt__SetAudioSourceConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'SetAudioEncoderConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__SetAudioEncoderConfiguration(_trt__SetAudioEncoderConfiguration *trt__SetAudioEncoderConfiguration, _trt__SetAudioEncoderConfigurationResponse *trt__SetAudioEncoderConfigurationResponse) { return soap ? soap_call___trt__SetAudioEncoderConfiguration(soap, endpoint, NULL, trt__SetAudioEncoderConfiguration, trt__SetAudioEncoderConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'SetVideoAnalyticsConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__SetVideoAnalyticsConfiguration(_trt__SetVideoAnalyticsConfiguration *trt__SetVideoAnalyticsConfiguration, _trt__SetVideoAnalyticsConfigurationResponse *trt__SetVideoAnalyticsConfigurationResponse) { return soap ? soap_call___trt__SetVideoAnalyticsConfiguration(soap, endpoint, NULL, trt__SetVideoAnalyticsConfiguration, trt__SetVideoAnalyticsConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'SetMetadataConfiguration' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__SetMetadataConfiguration(_trt__SetMetadataConfiguration *trt__SetMetadataConfiguration, _trt__SetMetadataConfigurationResponse *trt__SetMetadataConfigurationResponse) { return soap ? soap_call___trt__SetMetadataConfiguration(soap, endpoint, NULL, trt__SetMetadataConfiguration, trt__SetMetadataConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'GetVideoSourceConfigurationOptions' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetVideoSourceConfigurationOptions(_trt__GetVideoSourceConfigurationOptions *trt__GetVideoSourceConfigurationOptions, _trt__GetVideoSourceConfigurationOptionsResponse *trt__GetVideoSourceConfigurationOptionsResponse) { return soap ? soap_call___trt__GetVideoSourceConfigurationOptions(soap, endpoint, NULL, trt__GetVideoSourceConfigurationOptions, trt__GetVideoSourceConfigurationOptionsResponse) : SOAP_EOM; };
	/// Invoke 'GetVideoEncoderConfigurationOptions' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetVideoEncoderConfigurationOptions(_trt__GetVideoEncoderConfigurationOptions *trt__GetVideoEncoderConfigurationOptions, _trt__GetVideoEncoderConfigurationOptionsResponse *trt__GetVideoEncoderConfigurationOptionsResponse) { return soap ? soap_call___trt__GetVideoEncoderConfigurationOptions(soap, endpoint, NULL, trt__GetVideoEncoderConfigurationOptions, trt__GetVideoEncoderConfigurationOptionsResponse) : SOAP_EOM; };
	/// Invoke 'GetAudioSourceConfigurationOptions' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetAudioSourceConfigurationOptions(_trt__GetAudioSourceConfigurationOptions *trt__GetAudioSourceConfigurationOptions, _trt__GetAudioSourceConfigurationOptionsResponse *trt__GetAudioSourceConfigurationOptionsResponse) { return soap ? soap_call___trt__GetAudioSourceConfigurationOptions(soap, endpoint, NULL, trt__GetAudioSourceConfigurationOptions, trt__GetAudioSourceConfigurationOptionsResponse) : SOAP_EOM; };
	/// Invoke 'GetAudioEncoderConfigurationOptions' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetAudioEncoderConfigurationOptions(_trt__GetAudioEncoderConfigurationOptions *trt__GetAudioEncoderConfigurationOptions, _trt__GetAudioEncoderConfigurationOptionsResponse *trt__GetAudioEncoderConfigurationOptionsResponse) { return soap ? soap_call___trt__GetAudioEncoderConfigurationOptions(soap, endpoint, NULL, trt__GetAudioEncoderConfigurationOptions, trt__GetAudioEncoderConfigurationOptionsResponse) : SOAP_EOM; };
	/// Invoke 'GetMetadataConfigurationOptions' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetMetadataConfigurationOptions(_trt__GetMetadataConfigurationOptions *trt__GetMetadataConfigurationOptions, _trt__GetMetadataConfigurationOptionsResponse *trt__GetMetadataConfigurationOptionsResponse) { return soap ? soap_call___trt__GetMetadataConfigurationOptions(soap, endpoint, NULL, trt__GetMetadataConfigurationOptions, trt__GetMetadataConfigurationOptionsResponse) : SOAP_EOM; };
	/// Invoke 'GetGuaranteedNumberOfVideoEncoderInstances' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetGuaranteedNumberOfVideoEncoderInstances(_trt__GetGuaranteedNumberOfVideoEncoderInstances *trt__GetGuaranteedNumberOfVideoEncoderInstances, _trt__GetGuaranteedNumberOfVideoEncoderInstancesResponse *trt__GetGuaranteedNumberOfVideoEncoderInstancesResponse) { return soap ? soap_call___trt__GetGuaranteedNumberOfVideoEncoderInstances(soap, endpoint, NULL, trt__GetGuaranteedNumberOfVideoEncoderInstances, trt__GetGuaranteedNumberOfVideoEncoderInstancesResponse) : SOAP_EOM; };
	/// Invoke 'GetStreamUri' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetStreamUri(_trt__GetStreamUri *trt__GetStreamUri, _trt__GetStreamUriResponse *trt__GetStreamUriResponse) { return soap ? soap_call___trt__GetStreamUri(soap, endpoint, NULL, trt__GetStreamUri, trt__GetStreamUriResponse) : SOAP_EOM; };
	/// Invoke 'StartMulticastStreaming' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__StartMulticastStreaming(_trt__StartMulticastStreaming *trt__StartMulticastStreaming, _trt__StartMulticastStreamingResponse *trt__StartMulticastStreamingResponse) { return soap ? soap_call___trt__StartMulticastStreaming(soap, endpoint, NULL, trt__StartMulticastStreaming, trt__StartMulticastStreamingResponse) : SOAP_EOM; };
	/// Invoke 'StopMulticastStreaming' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__StopMulticastStreaming(_trt__StopMulticastStreaming *trt__StopMulticastStreaming, _trt__StopMulticastStreamingResponse *trt__StopMulticastStreamingResponse) { return soap ? soap_call___trt__StopMulticastStreaming(soap, endpoint, NULL, trt__StopMulticastStreaming, trt__StopMulticastStreamingResponse) : SOAP_EOM; };
	/// Invoke 'SetSynchronizationPoint' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__SetSynchronizationPoint(_trt__SetSynchronizationPoint *trt__SetSynchronizationPoint, _trt__SetSynchronizationPointResponse *trt__SetSynchronizationPointResponse) { return soap ? soap_call___trt__SetSynchronizationPoint(soap, endpoint, NULL, trt__SetSynchronizationPoint, trt__SetSynchronizationPointResponse) : SOAP_EOM; };
	/// Invoke 'GetSnapshotUri' of service 'MediaBinding' and return error code (or SOAP_OK)
	virtual int __trt__GetSnapshotUri(_trt__GetSnapshotUri *trt__GetSnapshotUri, _trt__GetSnapshotUriResponse *trt__GetSnapshotUriResponse) { return soap ? soap_call___trt__GetSnapshotUri(soap, endpoint, NULL, trt__GetSnapshotUri, trt__GetSnapshotUriResponse) : SOAP_EOM; };
};
#endif
