/* soapImagingBindingProxy.h
   Generated by gSOAP 2.8.0 from Onvif.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapImagingBindingProxy_H
#define soapImagingBindingProxy_H
#include "soapH.h"
class ImagingBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'ImagingBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	ImagingBinding()
	{ soap = soap_new(); endpoint = "http://localhost:80"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
	{"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
	{"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
	{"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
	{"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
	{"ns5", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL},
	{"ns6", "http://schemas.xmlsoap.org/ws/2005/04/discovery", NULL, NULL},
	{"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
	{"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
	{"tt", "http://www.onvif.org/ver10/schema", NULL, NULL},
	{"ns2", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
	{"wsa", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL, NULL},
	{"ns3", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
	{"ns10", "http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding", NULL, NULL},
	{"ns11", "http://www.onvif.org/ver10/events/wsdl/EventBinding", NULL, NULL},
	{"tev", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL},
	{"ns12", "http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding", NULL, NULL},
	{"ns13", "http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding", NULL, NULL},
	{"ns14", "http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding", NULL, NULL},
	{"ns15", "http://www.onvif.org/ver10/events/wsdl/PullPointBinding", NULL, NULL},
	{"ns16", "http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding", NULL, NULL},
	{"ns17", "http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding", NULL, NULL},
	{"ns1", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
	{"ns18", "http://www.onvif.org/ver10/network/wsdl/RemoteDiscoveryBinding", NULL, NULL},
	{"ns19", "http://www.onvif.org/ver10/network/wsdl/DiscoveryLookupBinding", NULL, NULL},
	{"dn", "http://www.onvif.org/ver10/network/wsdl", NULL, NULL},
	{"ns8", "http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding", NULL, NULL},
	{"ns9", "http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding", NULL, NULL},
	{"tan", "http://www.onvif.org/ver20/analytics/wsdl", NULL, NULL},
	{"tds", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL},
	{"timg", "http://www.onvif.org/ver20/imaging/wsdl", NULL, NULL},
	{"tptz", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
	{"trt", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~ImagingBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'GetImagingSettings' of service 'ImagingBinding' and return error code (or SOAP_OK)
	virtual int __timg__GetImagingSettings(_timg__GetImagingSettings *timg__GetImagingSettings, _timg__GetImagingSettingsResponse *timg__GetImagingSettingsResponse) { return soap ? soap_call___timg__GetImagingSettings(soap, endpoint, NULL, timg__GetImagingSettings, timg__GetImagingSettingsResponse) : SOAP_EOM; };
	/// Invoke 'SetImagingSettings' of service 'ImagingBinding' and return error code (or SOAP_OK)
	virtual int __timg__SetImagingSettings(_timg__SetImagingSettings *timg__SetImagingSettings, _timg__SetImagingSettingsResponse *timg__SetImagingSettingsResponse) { return soap ? soap_call___timg__SetImagingSettings(soap, endpoint, NULL, timg__SetImagingSettings, timg__SetImagingSettingsResponse) : SOAP_EOM; };
	/// Invoke 'GetOptions' of service 'ImagingBinding' and return error code (or SOAP_OK)
	virtual int __timg__GetOptions(_timg__GetOptions *timg__GetOptions, _timg__GetOptionsResponse *timg__GetOptionsResponse) { return soap ? soap_call___timg__GetOptions(soap, endpoint, NULL, timg__GetOptions, timg__GetOptionsResponse) : SOAP_EOM; };
	/// Invoke 'Move' of service 'ImagingBinding' and return error code (or SOAP_OK)
	virtual int __timg__Move(_timg__Move *timg__Move, _timg__MoveResponse *timg__MoveResponse) { return soap ? soap_call___timg__Move(soap, endpoint, NULL, timg__Move, timg__MoveResponse) : SOAP_EOM; };
	/// Invoke 'Stop' of service 'ImagingBinding' and return error code (or SOAP_OK)
	virtual int __timg__Stop(_timg__Stop *timg__Stop, _timg__StopResponse *timg__StopResponse) { return soap ? soap_call___timg__Stop(soap, endpoint, NULL, timg__Stop, timg__StopResponse) : SOAP_EOM; };
	/// Invoke 'GetStatus' of service 'ImagingBinding' and return error code (or SOAP_OK)
	virtual int __timg__GetStatus(_timg__GetStatus *timg__GetStatus, _timg__GetStatusResponse *timg__GetStatusResponse) { return soap ? soap_call___timg__GetStatus(soap, endpoint, NULL, timg__GetStatus, timg__GetStatusResponse) : SOAP_EOM; };
	/// Invoke 'GetMoveOptions' of service 'ImagingBinding' and return error code (or SOAP_OK)
	virtual int __timg__GetMoveOptions(_timg__GetMoveOptions *timg__GetMoveOptions, _timg__GetMoveOptionsResponse *timg__GetMoveOptionsResponse) { return soap ? soap_call___timg__GetMoveOptions(soap, endpoint, NULL, timg__GetMoveOptions, timg__GetMoveOptionsResponse) : SOAP_EOM; };
};
#endif
