/* soapPTZBindingProxy.h
   Generated by gSOAP 2.8.0 from Onvif.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapPTZBindingProxy_H
#define soapPTZBindingProxy_H
#include "soapH.h"
class PTZBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'PTZBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	PTZBinding()
	{ soap = soap_new(); endpoint = "http://localhost:80"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
	{"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
	{"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
	{"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
	{"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
	{"ns5", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL},
	{"ns6", "http://schemas.xmlsoap.org/ws/2005/04/discovery", NULL, NULL},
	{"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
	{"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
	{"tt", "http://www.onvif.org/ver10/schema", NULL, NULL},
	{"ns2", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
	{"wsa", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL, NULL},
	{"ns3", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
	{"ns10", "http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding", NULL, NULL},
	{"ns11", "http://www.onvif.org/ver10/events/wsdl/EventBinding", NULL, NULL},
	{"tev", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL},
	{"ns12", "http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding", NULL, NULL},
	{"ns13", "http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding", NULL, NULL},
	{"ns14", "http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding", NULL, NULL},
	{"ns15", "http://www.onvif.org/ver10/events/wsdl/PullPointBinding", NULL, NULL},
	{"ns16", "http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding", NULL, NULL},
	{"ns17", "http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding", NULL, NULL},
	{"ns1", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
	{"ns18", "http://www.onvif.org/ver10/network/wsdl/RemoteDiscoveryBinding", NULL, NULL},
	{"ns19", "http://www.onvif.org/ver10/network/wsdl/DiscoveryLookupBinding", NULL, NULL},
	{"dn", "http://www.onvif.org/ver10/network/wsdl", NULL, NULL},
	{"ns8", "http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding", NULL, NULL},
	{"ns9", "http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding", NULL, NULL},
	{"tan", "http://www.onvif.org/ver20/analytics/wsdl", NULL, NULL},
	{"tds", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL},
	{"timg", "http://www.onvif.org/ver20/imaging/wsdl", NULL, NULL},
	{"tptz", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
	{"trt", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~PTZBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'GetConfigurations' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__GetConfigurations(_tptz__GetConfigurations *tptz__GetConfigurations, _tptz__GetConfigurationsResponse *tptz__GetConfigurationsResponse) { return soap ? soap_call___tptz__GetConfigurations(soap, endpoint, NULL, tptz__GetConfigurations, tptz__GetConfigurationsResponse) : SOAP_EOM; };
	/// Invoke 'GetPresets' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__GetPresets(_tptz__GetPresets *tptz__GetPresets, _tptz__GetPresetsResponse *tptz__GetPresetsResponse) { return soap ? soap_call___tptz__GetPresets(soap, endpoint, NULL, tptz__GetPresets, tptz__GetPresetsResponse) : SOAP_EOM; };
	/// Invoke 'SetPreset' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__SetPreset(_tptz__SetPreset *tptz__SetPreset, _tptz__SetPresetResponse *tptz__SetPresetResponse) { return soap ? soap_call___tptz__SetPreset(soap, endpoint, NULL, tptz__SetPreset, tptz__SetPresetResponse) : SOAP_EOM; };
	/// Invoke 'RemovePreset' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__RemovePreset(_tptz__RemovePreset *tptz__RemovePreset, _tptz__RemovePresetResponse *tptz__RemovePresetResponse) { return soap ? soap_call___tptz__RemovePreset(soap, endpoint, NULL, tptz__RemovePreset, tptz__RemovePresetResponse) : SOAP_EOM; };
	/// Invoke 'GotoPreset' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__GotoPreset(_tptz__GotoPreset *tptz__GotoPreset, _tptz__GotoPresetResponse *tptz__GotoPresetResponse) { return soap ? soap_call___tptz__GotoPreset(soap, endpoint, NULL, tptz__GotoPreset, tptz__GotoPresetResponse) : SOAP_EOM; };
	/// Invoke 'GetStatus' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__GetStatus(_tptz__GetStatus *tptz__GetStatus, _tptz__GetStatusResponse *tptz__GetStatusResponse) { return soap ? soap_call___tptz__GetStatus(soap, endpoint, NULL, tptz__GetStatus, tptz__GetStatusResponse) : SOAP_EOM; };
	/// Invoke 'GetConfiguration' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__GetConfiguration(_tptz__GetConfiguration *tptz__GetConfiguration, _tptz__GetConfigurationResponse *tptz__GetConfigurationResponse) { return soap ? soap_call___tptz__GetConfiguration(soap, endpoint, NULL, tptz__GetConfiguration, tptz__GetConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'GetNodes' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__GetNodes(_tptz__GetNodes *tptz__GetNodes, _tptz__GetNodesResponse *tptz__GetNodesResponse) { return soap ? soap_call___tptz__GetNodes(soap, endpoint, NULL, tptz__GetNodes, tptz__GetNodesResponse) : SOAP_EOM; };
	/// Invoke 'GetNode' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__GetNode(_tptz__GetNode *tptz__GetNode, _tptz__GetNodeResponse *tptz__GetNodeResponse) { return soap ? soap_call___tptz__GetNode(soap, endpoint, NULL, tptz__GetNode, tptz__GetNodeResponse) : SOAP_EOM; };
	/// Invoke 'SetConfiguration' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__SetConfiguration(_tptz__SetConfiguration *tptz__SetConfiguration, _tptz__SetConfigurationResponse *tptz__SetConfigurationResponse) { return soap ? soap_call___tptz__SetConfiguration(soap, endpoint, NULL, tptz__SetConfiguration, tptz__SetConfigurationResponse) : SOAP_EOM; };
	/// Invoke 'GetConfigurationOptions' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__GetConfigurationOptions(_tptz__GetConfigurationOptions *tptz__GetConfigurationOptions, _tptz__GetConfigurationOptionsResponse *tptz__GetConfigurationOptionsResponse) { return soap ? soap_call___tptz__GetConfigurationOptions(soap, endpoint, NULL, tptz__GetConfigurationOptions, tptz__GetConfigurationOptionsResponse) : SOAP_EOM; };
	/// Invoke 'GotoHomePosition' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__GotoHomePosition(_tptz__GotoHomePosition *tptz__GotoHomePosition, _tptz__GotoHomePositionResponse *tptz__GotoHomePositionResponse) { return soap ? soap_call___tptz__GotoHomePosition(soap, endpoint, NULL, tptz__GotoHomePosition, tptz__GotoHomePositionResponse) : SOAP_EOM; };
	/// Invoke 'SetHomePosition' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__SetHomePosition(_tptz__SetHomePosition *tptz__SetHomePosition, _tptz__SetHomePositionResponse *tptz__SetHomePositionResponse) { return soap ? soap_call___tptz__SetHomePosition(soap, endpoint, NULL, tptz__SetHomePosition, tptz__SetHomePositionResponse) : SOAP_EOM; };
	/// Invoke 'ContinuousMove' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__ContinuousMove(_tptz__ContinuousMove *tptz__ContinuousMove, _tptz__ContinuousMoveResponse *tptz__ContinuousMoveResponse) { return soap ? soap_call___tptz__ContinuousMove(soap, endpoint, NULL, tptz__ContinuousMove, tptz__ContinuousMoveResponse) : SOAP_EOM; };
	/// Invoke 'RelativeMove' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__RelativeMove(_tptz__RelativeMove *tptz__RelativeMove, _tptz__RelativeMoveResponse *tptz__RelativeMoveResponse) { return soap ? soap_call___tptz__RelativeMove(soap, endpoint, NULL, tptz__RelativeMove, tptz__RelativeMoveResponse) : SOAP_EOM; };
	/// Invoke 'SendAuxiliaryCommand' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__SendAuxiliaryCommand(_tptz__SendAuxiliaryCommand *tptz__SendAuxiliaryCommand, _tptz__SendAuxiliaryCommandResponse *tptz__SendAuxiliaryCommandResponse) { return soap ? soap_call___tptz__SendAuxiliaryCommand(soap, endpoint, NULL, tptz__SendAuxiliaryCommand, tptz__SendAuxiliaryCommandResponse) : SOAP_EOM; };
	/// Invoke 'AbsoluteMove' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__AbsoluteMove(_tptz__AbsoluteMove *tptz__AbsoluteMove, _tptz__AbsoluteMoveResponse *tptz__AbsoluteMoveResponse) { return soap ? soap_call___tptz__AbsoluteMove(soap, endpoint, NULL, tptz__AbsoluteMove, tptz__AbsoluteMoveResponse) : SOAP_EOM; };
	/// Invoke 'Stop' of service 'PTZBinding' and return error code (or SOAP_OK)
	virtual int __tptz__Stop(_tptz__Stop *tptz__Stop, _tptz__StopResponse *tptz__StopResponse) { return soap ? soap_call___tptz__Stop(soap, endpoint, NULL, tptz__Stop, tptz__StopResponse) : SOAP_EOM; };
};
#endif
